before_all do
    ensure_git_branch
    ensure_git_status_clean
    git_pull
end

platform :ios do
    desc "Try to test app"
    private_lane :staging_build do
        increment_build_number_in_plist(xcodeproj: '../ios/MyApp.xcodeproj', target: 'MyApp')
        gym(scheme:'MyApp', workspace: '../ios/MyApp.xcworkspace')
    end
    lane :beta do
        staging_build     
    end
end